"""lessons orm

Revision ID: 67af606d92d5
Revises: 
Create Date: 2026-03-03 09:26:47.872349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67af606d92d5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lessons',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('course', sa.String(length=1024), nullable=False),
    sa.Column('course_degree', sa.Integer(), nullable=False),
    sa.Column('file_url', sa.String(length=2048), nullable=False),
    sa.Column('pk', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('pk')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lessons')
    # ### end Alembic commands ###
