"""lessons and category

Revision ID: bc7d38d59208
Revises: 
Create Date: 2026-03-03 20:00:39.660819

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc7d38d59208'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('course_degree', sa.Integer(), nullable=False),
    sa.Column('pk', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('pk')
    )
    op.create_table('lessons',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('file_url', sa.String(length=2048), nullable=False),
    sa.Column('category', sa.Integer(), nullable=False),
    sa.Column('pk', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category'], ['category.pk'], ),
    sa.PrimaryKeyConstraint('pk')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lessons')
    op.drop_table('category')
    # ### end Alembic commands ###
